server:
  port: 8180
  compression:
    enabled: true

spring:
  profiles:
    active: prod

backend:
  scheme: http
  host: localhost
  port: 8280
  security:
    jwt:
        client-id: website
        client-secret: XY7kmzoNzl100

---

spring:
    profiles: dev

logging:
  level:
    fr.cph.crypto.gateway: DEBUG

---

spring:
    profiles: prod

logging:
  level:
    fr.cph.crypto.gateway: INFO
  file: gateway.log