security:
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  jwt:
    client-id: website
    client-secret: XY7kmzoNzl100
    resource-id: backendresource
    grant-types:
      - password
      - client_credentials
    scopes:
      - read
      - write
  oauth2:
    resource:
      filter-order: 3

spring:
  data:
    mongodb:
      database: cryptodb
      repositories:
        enabled: true
  profiles:
    active: prod

server:
  port: 8280
  compression:
    enabled: true

---

spring:
    profiles: dev

logging:
  level:
    fr.cph.crypto: DEBUG
    org.springframework.security: INFO

---

spring:
    profiles: prod

logging:
  level:
    fr.cph.crypto: INFO
    org.springframework.security: INFO
  file: back-end.log